default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: tower_development
  primary_replica:
    <<: *default
    database: tower_development

test:
  primary:
    <<: *default
    database: tower_test
  primary_replica:
    <<: *default
    database: tower_test

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    url: <%= ENV['DATABASE_URL'] %>
